# Generated by Django 3.0.3 on 2020-03-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='tickerlong',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.TextField(),
        ),
    ]
