# Generated by Django 3.0.3 on 2020-04-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20200415_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='user',
        ),
        migrations.AddField(
            model_name='stock',
            name='user_whole_name',
            field=models.TextField(default='default'),
        ),
    ]
